services:
  documentserver:
    image: onlyoffice/documentserver
    ports:
      - 4003:80
    volumes:
      - ./.docker/logs:/var/log/onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=JWT_SECRET
      - GENERATE_FONTS=true
