name: Staging health checks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Install Playwright browser
        run: npx playwright install --with-deps
      - name: Run health check
        run: yarn workspace ops test
        env:
          URL: https://seeds.bleumatin.fr
          EMAIL: prod@bleumatin.fr
          PASSWORD: ${{ secrets.STAGING_HEALTH_CHECK_PASSWORD }}
      - name: Failure notification
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_MONITORING_WEBHOOK }}
        with:
          args: 'The Health Check has failed for SEEDS Staging'
      - name: Framateam failure notification
        if: ${{ failure() }}
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.FRAMATEAM_MONITORING_WEBHOOK }}
          TEXT: |
            :warning: The Health Check has failed for SEEDS Staging
            [View workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
