name: Publish on GHCR
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Logging into docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin registry.bleumatin.fr

      - name: Pulling image
        run: docker pull registry.bleumatin.fr/arviva/seeds:${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tagging to version
        run: |
          docker image tag registry.bleumatin.fr/arviva/seeds:${GITHUB_SHA} ghcr.io/bleumatin-fr/seeds:${GITHUB_REF#refs/tags/}
          docker image tag registry.bleumatin.fr/arviva/seeds:${GITHUB_SHA} ghcr.io/bleumatin-fr/seeds:latest

      - name: Pushing to GitHub Container Registry
        run: docker push --all-tags ghcr.io/bleumatin-fr/seeds

      - name: Restarting
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /seeds &&
            docker compose down &&
            docker compose pull &&
            docker compose up -d
