name: Production deployment
on:
  push:
    tags:
      - v*

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Logging in to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Pulling image
        run: docker pull ${{ secrets.PRIVATE_REGISTRY_URL }}/arviva/seeds:${GITHUB_SHA}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tagging to version
        run: |
          docker image tag ${{ secrets.PRIVATE_REGISTRY_URL }}/arviva/seeds:${GITHUB_SHA} ghcr.io/bleumatin-fr/seeds:${GITHUB_REF#refs/tags/}
          docker image tag ${{ secrets.PRIVATE_REGISTRY_URL }}/arviva/seeds:${GITHUB_SHA} ghcr.io/bleumatin-fr/seeds:latest

      - name: Pushing to GitHub Container Registry
        run: docker push --all-tags ghcr.io/bleumatin-fr/seeds

      - name: Restarting
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          key: ${{ secrets.PRODUCTION_SERVER_KEY }}
          script: |
            cd /seeds &&
            docker compose down &&
            docker compose pull &&
            docker compose up -d
