name: Staging deployment

on:  
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Logging in to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
          username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

      - name: Building
        run: docker build --no-cache --tag ${{ secrets.PRIVATE_REGISTRY_URL }}/arviva/seeds:latest --tag ${{ secrets.PRIVATE_REGISTRY_URL }}/arviva/seeds:${GITHUB_SHA} .

      - name: Deploying
        run: docker push --all-tags ${{ secrets.PRIVATE_REGISTRY_URL }}/arviva/seeds

      - name: Restarting
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_KEY }}
          script: sudo bash -c "cd /home/debian/portainer/data/compose/6/ && docker compose -p arviva-seeds down && docker compose -p arviva-seeds pull && docker compose -p arviva-seeds up -d"
